"""criar morador condominioss id

Revision ID: 0521b103e8af
Revises: 
Create Date: 2025-11-17 10:44:22.978849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0521b103e8af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ambientes_condominio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('id_condominio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morador_condominio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_condominio', sa.Integer(), nullable=True),
    sa.Column('id_morador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['id_morador'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sindico_condominio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_condominio', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('dataCriacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sindico_condominio')
    op.drop_table('morador_condominio')
    op.drop_table('ambientes_condominio')
    op.drop_table('usuarios')
    op.drop_table('condominios')
    # ### end Alembic commands ###
