"""criar tabelas reservas

Revision ID: 2245dbb3c542
Revises: 
Create Date: 2025-11-26 13:43:52.073801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2245dbb3c542'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tabela', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ambientes_condominio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('id_condominio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morador_condominio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_condominio', sa.Integer(), nullable=True),
    sa.Column('id_morador', sa.Integer(), nullable=True),
    sa.Column('apartamento', sa.String(), nullable=True),
    sa.Column('torre', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['id_morador'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sindico_condominio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_condominio', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('dataCriacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('apto', sa.String(), nullable=False),
    sa.Column('id_condominio', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('data_visita', sa.Date(), nullable=True),
    sa.Column('hora_visita', sa.Time(), nullable=True),
    sa.Column('confirmado', sa.String(), nullable=True),
    sa.Column('cancelado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva_ambiente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ambiente', sa.Integer(), nullable=True),
    sa.Column('id_morador', sa.Integer(), nullable=True),
    sa.Column('id_condominio', sa.Integer(), nullable=True),
    sa.Column('data_reserva', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_ambiente'], ['ambientes_condominio.id'], ),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['id_morador'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva_ambiente')
    op.drop_table('visitas')
    op.drop_table('sindico_condominio')
    op.drop_table('morador_condominio')
    op.drop_table('ambientes_condominio')
    op.drop_table('usuarios')
    op.drop_table('status')
    op.drop_table('pessoas')
    op.drop_table('condominios')
    # ### end Alembic commands ###
