"""criar tabelas

Revision ID: 3149a48c52ff
Revises: 2245dbb3c542
Create Date: 2025-11-26 22:22:34.285919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3149a48c52ff'
down_revision: Union[str, Sequence[str], None] = '2245dbb3c542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_condominio', sa.Integer(), nullable=True),
    sa.Column('id_ambiente', sa.Integer(), nullable=True),
    sa.Column('apto', sa.String(), nullable=True),
    sa.Column('torre', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.Column('aprovado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_ambiente'], ['ambientes_condominio.id'], ),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestador_servico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=True),
    sa.Column('id_servico', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['id_servico'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestador_servico')
    op.drop_table('servicos')
    # ### end Alembic commands ###
