"""criar tabelas reservas

Revision ID: 8c89574408e3
Revises: cb9d1a15a7f8
Create Date: 2025-11-21 11:19:50.777984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c89574408e3'
down_revision: Union[str, Sequence[str], None] = 'cb9d1a15a7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tabela', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva_ambiente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ambiente', sa.Integer(), nullable=True),
    sa.Column('id_morador', sa.Integer(), nullable=True),
    sa.Column('id_condominio', sa.Integer(), nullable=True),
    sa.Column('data_reserva', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_ambiente'], ['ambientes_condominio.id'], ),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['id_morador'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ambientes_condominio', sa.Column('info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ambientes_condominio', 'info')
    op.drop_table('reserva_ambiente')
    op.drop_table('status')
    # ### end Alembic commands ###
