"""tabelas de pessoas e visitas

Revision ID: adf2c607e83d
Revises: 8c89574408e3
Create Date: 2025-11-24 16:08:18.830637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf2c607e83d'
down_revision: Union[str, Sequence[str], None] = '8c89574408e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.Column('apto', sa.String(), nullable=False),
    sa.Column('id_condominio', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitas')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
