"""inserção 

Revision ID: cb9d1a15a7f8
Revises: dcd377cde5cb
Create Date: 2025-11-18 18:42:53.604174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9d1a15a7f8'
down_revision: Union[str, Sequence[str], None] = 'dcd377cde5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('telefone', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('cpf', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'cpf')
    op.drop_column('usuarios', 'telefone')
    # ### end Alembic commands ###
