"""inserção de colunas

Revision ID: dcd377cde5cb
Revises: 0521b103e8af
Create Date: 2025-11-18 18:25:40.903623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd377cde5cb'
down_revision: Union[str, Sequence[str], None] = '0521b103e8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('morador_condominio', sa.Column('apartamento', sa.String(), nullable=True))
    op.add_column('morador_condominio', sa.Column('torre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('morador_condominio', 'torre')
    op.drop_column('morador_condominio', 'apartamento')
    # ### end Alembic commands ###
